CREATE TABLE IF NOT EXISTS public.bookings (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    service_id uuid NOT NULL,
    consumer_id uuid NOT NULL,
    provider_id uuid NOT NULL,
    status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text])),
    booking_date timestamp with time zone NOT NULL,
    -- Enhanced booking fields from Phase 2
    scheduled_date date NOT NULL,
    scheduled_time time without time zone NOT NULL,
    duration_hours numeric DEFAULT 1.0,
    location_address text NOT NULL,
    customer_phone character varying,
    customer_email character varying,
    special_instructions text,
    estimated_price numeric,
    actual_price numeric,
    payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
    payment_method character varying CHECK (payment_method::text = ANY (ARRAY['cash'::character varying, 'online'::character varying, 'card'::character varying, 'wallet'::character varying]::text[])),
    created_by_consumer boolean DEFAULT true,
    booking_reference character varying UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    tokens_awarded boolean DEFAULT false,
    token_award_amount bigint DEFAULT 0,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
    CONSTRAINT bookings_consumer_id_fkey FOREIGN KEY (consumer_id) REFERENCES public.profiles(id),
    CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.profiles(id)
); 